---
version: '3.8'
name: expense
#if you want to create and use a new network use below
networks:
  default:
    name: expense
    #or
  #networks: 
    #- expense #it will use the existed network
services:
  mysql:
    image: mysql:v1.0
    container_name: mysql
    networks: 
      - expense
    volumes:
      - testvo1:  /var/lib/mysql

    backend:
      image: backend:v1.0
      container_name: backend
      depends_on:
        - mysql

    frontend:
      image: frontend:v1.0
      container_name: frontend
      networks: expense
      depends_on: 
        - backend
      ports: 
      - "3306:3306"


  #services: ['mysql: {image: mysql:v1.0, container_name: mysql}', 'frontend: {frontend:v1.0, container_name: frontend}', 'backend: {backend:v1.0, container_name: backend}']

